MONGODB_USERNAME = 'MONGODB_USERNAME'
MONGODB_PASSWORD = 'MONGODB_PASSWORD'

MONGODB_HOST = 'MONGODB_HOST'
MONGODB_PORT = 'MONGODB_PORT'

MONGODB_DATABASE = 'MONGODB_DATABASE'
MONGODB_COLLECTION = 'MONGODB_COLLECTION'

MONGODB_OPTIONS_ = 'MONGODB_OPTIONS_'

MONGODB_INDEXES = 'MONGODB_INDEXES'

MONGODB_PROCESS_ITEM = 'MONGODB_PROCESS_ITEM'
